[platformio]
name = "camera-stream"
description = "Set up the OV7670 module and report image data over serial."

[env:arduino]
platform = atmelavr
board = uno

board_build.mcu = atmega328p
board_build.f_cpu = 16000000L

upload_protocol = arduino
upload_speed = 115200

build_unflags = -std=gnu++11
build_flags = -std=c++14