# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor/alerts.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'sensor/alerts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13sensor/alerts.proto\x12\x06sensor*\xbe\x01\n\x05\x41lert\x12\x13\n\x0fLOW_INPUT_POWER\x10\x00\x12\x12\n\x0eNO_INPUT_POWER\x10\x01\x12\x0e\n\nLOW_CHARGE\x10\x02\x12\x1d\n\x19\x43\x41MERA_NOT_RESPONDING_I2C\x10\x10\x12\x18\n\x14\x43\x41MERA_IMAGE_TIMEOUT\x10\x11\x12\x18\n\x14\x46PGA_NOT_CONFIGURING\x10 \x12\x15\n\x11\x46PGA_DATA_TIMEOUT\x10!\x12\x12\n\x0eWATCHDOG_RESET\x10\x30\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor.alerts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ALERT']._serialized_start=32
  _globals['_ALERT']._serialized_end=222
# @@protoc_insertion_point(module_scope)
