# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor/camera.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'sensor/camera.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13sensor/camera.proto\x12\rsensor.camera\"z\n\x06Status\x12#\n\x05state\x18\x01 \x01(\x0e\x32\x14.sensor.camera.State\x12\x36\n\x10\x63urrent_settings\x18\x02 \x01(\x0b\x32\x17.sensor.camera.SettingsH\x00\x88\x01\x01\x42\x13\n\x11_current_settings\"\x9b\x01\n\x07\x43ommand\x12\x14\n\x0c\x65nable_power\x18\x01 \x01(\x08\x12*\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x15.sensor.camera.ActionH\x00\x88\x01\x01\x12\x32\n\x0cnew_settings\x18\x03 \x01(\x0b\x32\x17.sensor.camera.SettingsH\x01\x88\x01\x01\x42\t\n\x07_actionB\x0f\n\r_new_settings\"\x1f\n\x08Settings\x12\x13\n\x0b\x65xposure_us\x18\x01 \x01(\r*\x80\x01\n\x05State\x12\x11\n\rSTATE_UNKNOWN\x10\x00\x12\r\n\tSTATE_OFF\x10\x01\x12\x11\n\rSTATE_BOOTING\x10\x02\x12\x15\n\x11STATE_CONFIGURING\x10\x03\x12\x11\n\rSTATE_RUNNING\x10\x04\x12\x18\n\x14STATE_LOW_POWER_IDLE\x10\x0f*R\n\x06\x41\x63tion\x12\x0f\n\x0b\x41\x43TION_NONE\x10\x00\x12\x0e\n\nACTION_RUN\x10\x01\x12\x16\n\x12\x41\x43TION_RECONFIGURE\x10\x02\x12\x0f\n\x0b\x41\x43TION_IDLE\x10\x0f\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor.camera_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATE']._serialized_start=354
  _globals['_STATE']._serialized_end=482
  _globals['_ACTION']._serialized_start=484
  _globals['_ACTION']._serialized_end=566
  _globals['_STATUS']._serialized_start=38
  _globals['_STATUS']._serialized_end=160
  _globals['_COMMAND']._serialized_start=163
  _globals['_COMMAND']._serialized_end=318
  _globals['_SETTINGS']._serialized_start=320
  _globals['_SETTINGS']._serialized_end=351
# @@protoc_insertion_point(module_scope)
