# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor/fpga.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'sensor/fpga.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sensor.fpga import flash_pb2 as sensor_dot_fpga_dot_flash__pb2
from sensor.fpga import image_pb2 as sensor_dot_fpga_dot_image__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sensor/fpga.proto\x12\x0bsensor.fpga\x1a\x17sensor/fpga/flash.proto\x1a\x17sensor/fpga/image.proto\"\x8a\x01\n\x06Status\x12!\n\x05state\x18\x01 \x01(\x0e\x32\x12.sensor.fpga.State\x12(\n\x05\x66lash\x18\x02 \x01(\x0b\x32\x19.sensor.fpga.flash.Status\x12*\n\x04line\x18\x03 \x01(\x0b\x32\x17.sensor.fpga.image.LineH\x00\x88\x01\x01\x42\x07\n\x05_line\"x\n\x07\x43ommand\x12(\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x13.sensor.fpga.ActionH\x00\x88\x01\x01\x12.\n\x05\x66lash\x18\x03 \x01(\x0b\x32\x1a.sensor.fpga.flash.CommandH\x01\x88\x01\x01\x42\t\n\x07_actionB\x08\n\x06_flash*~\n\x05State\x12\x11\n\rSTATE_UNKNOWN\x10\x00\x12\r\n\tSTATE_OFF\x10\x01\x12\x11\n\rSTATE_BOOTING\x10\x02\x12\x11\n\rSTATE_RUNNING\x10\x03\x12\x13\n\x0fSTATE_SPI_FLASH\x10\x0e\x12\x18\n\x14STATE_LOW_POWER_IDLE\x10\x0f*S\n\x06\x41\x63tion\x12\x0f\n\x0b\x41\x43TION_NONE\x10\x00\x12\x0e\n\nACTION_OFF\x10\x01\x12\x12\n\x0e\x41\x43TION_CAPTURE\x10\x02\x12\x14\n\x10\x41\x43TION_SPI_FLASH\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor.fpga_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATE']._serialized_start=347
  _globals['_STATE']._serialized_end=473
  _globals['_ACTION']._serialized_start=475
  _globals['_ACTION']._serialized_end=558
  _globals['_STATUS']._serialized_start=85
  _globals['_STATUS']._serialized_end=223
  _globals['_COMMAND']._serialized_start=225
  _globals['_COMMAND']._serialized_end=345
# @@protoc_insertion_point(module_scope)
