# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor/fpga/flash.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'sensor/fpga/flash.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17sensor/fpga/flash.proto\x12\x11sensor.fpga.flash\"\xb9\x01\n\x06Status\x12,\n\x05state\x18\x01 \x01(\x0e\x32\x18.sensor.fpga.flash.StateH\x00\x88\x01\x01\x12\x1d\n\x10stm_page_request\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x32\n\x0creadout_page\x18\x03 \x01(\x0b\x32\x17.sensor.fpga.flash.PageH\x02\x88\x01\x01\x42\x08\n\x06_stateB\x13\n\x11_stm_page_requestB\x0f\n\r_readout_page\"\xed\x01\n\x07\x43ommand\x12.\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x19.sensor.fpga.flash.ActionH\x00\x88\x01\x01\x12\x30\n\x07segment\x18\x02 \x01(\x0e\x32\x1a.sensor.fpga.flash.SegmentH\x01\x88\x01\x01\x12*\n\x04page\x18\x03 \x01(\x0b\x32\x17.sensor.fpga.flash.PageH\x02\x88\x01\x01\x12\x1e\n\x11host_page_request\x18\x04 \x01(\rH\x03\x88\x01\x01\x42\t\n\x07_actionB\n\n\x08_segmentB\x07\n\x05_pageB\x14\n\x12_host_page_request\"f\n\x04Page\x12\x18\n\x0bpage_number\x18\x01 \x01(\rH\x00\x88\x01\x01\x12\x11\n\x04\x64\x61ta\x18\x02 \x01(\x0cH\x01\x88\x01\x01\x12\x10\n\x03\x63rc\x18\x03 \x01(\x07H\x02\x88\x01\x01\x42\x0e\n\x0c_page_numberB\x07\n\x05_dataB\x06\n\x04_crc*v\n\x05State\x12\x11\n\rSTATE_UNKNOWN\x10\x00\x12\r\n\tSTATE_OFF\x10\x01\x12\x11\n\rSTATE_ERASING\x10\x02\x12\x15\n\x11STATE_PROGRAMMING\x10\x03\x12\x11\n\rSTATE_READOUT\x10\x04\x12\x0e\n\nSTATE_DONE\x10\x05*A\n\x06\x41\x63tion\x12\x0f\n\x0b\x41\x43TION_NONE\x10\x00\x12\x12\n\x0e\x41\x43TION_PROGRAM\x10\x01\x12\x12\n\x0e\x41\x43TION_READOUT\x10\x02*\xa1\x01\n\x07Segment\x12\x13\n\x0fSEGMENT_UNKNOWN\x10\x00\x12\x10\n\x0cSEGMENT_FPGA\x10\x01\x12\x11\n\rSEGMENT_QVGA0\x10\x02\x12\x11\n\rSEGMENT_QVGA1\x10\x03\x12\x11\n\rSEGMENT_QVGA2\x10\x04\x12\x11\n\rSEGMENT_QVGA3\x10\x05\x12\x11\n\rSEGMENT_QVGA4\x10\x06\x12\x10\n\x0cSEGMENT_USER\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor.fpga.flash_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATE']._serialized_start=578
  _globals['_STATE']._serialized_end=696
  _globals['_ACTION']._serialized_start=698
  _globals['_ACTION']._serialized_end=763
  _globals['_SEGMENT']._serialized_start=766
  _globals['_SEGMENT']._serialized_end=927
  _globals['_STATUS']._serialized_start=47
  _globals['_STATUS']._serialized_end=232
  _globals['_COMMAND']._serialized_start=235
  _globals['_COMMAND']._serialized_end=472
  _globals['_PAGE']._serialized_start=474
  _globals['_PAGE']._serialized_end=576
# @@protoc_insertion_point(module_scope)
