# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sensor import camera_pb2 as sensor_dot_camera__pb2
from sensor import fpga_pb2 as sensor_dot_fpga__pb2
from sensor import measure_pb2 as sensor_dot_measure__pb2
from sensor import parameters_pb2 as sensor_dot_parameters__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\x12\x06sensor\x1a\x13sensor/camera.proto\x1a\x11sensor/fpga.proto\x1a\x14sensor/measure.proto\x1a\x17sensor/parameters.proto\"\xa3\x01\n\x07\x43ommand\x12#\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x0e.sensor.ActionH\x00\x88\x01\x01\x12\'\n\x04\x66pga\x18\x02 \x01(\x0b\x32\x14.sensor.fpga.CommandH\x01\x88\x01\x01\x12+\n\x06\x63\x61mera\x18\x03 \x01(\x0b\x32\x16.sensor.camera.CommandH\x02\x88\x01\x01\x42\t\n\x07_actionB\x07\n\x05_fpgaB\t\n\x07_camera\"\x98\x02\n\x06Status\x12\x1c\n\x05state\x18\x01 \x01(\x0e\x32\r.sensor.State\x12(\n\x0bmeasurement\x18\x02 \x01(\x0b\x32\x13.sensor.Measurement\x12\x0e\n\x06\x61lerts\x18\x03 \x01(\x06\x12&\n\x04\x66pga\x18\x04 \x01(\x0b\x32\x13.sensor.fpga.StatusH\x00\x88\x01\x01\x12*\n\x06\x63\x61mera\x18\x05 \x01(\x0b\x32\x15.sensor.camera.StatusH\x01\x88\x01\x01\x12\x17\n\ntx_counter\x18\x0e \x01(\rH\x02\x88\x01\x01\x12\x17\n\nrx_counter\x18\x0f \x01(\rH\x03\x88\x01\x01\x42\x07\n\x05_fpgaB\t\n\x07_cameraB\r\n\x0b_tx_counterB\r\n\x0b_rx_counter*i\n\x05State\x12\x11\n\rSTATE_UNKNOWN\x10\x00\x12\x10\n\x0cSTATE_MANUAL\x10\x01\x12\x12\n\x0eSTATE_CHARGING\x10\x02\x12\x11\n\rSTATE_CAPTURE\x10\x03\x12\x14\n\x10STATE_LOW_CHARGE\x10\x04*@\n\x06\x41\x63tion\x12\x0f\n\x0b\x41\x43TION_NONE\x10\x00\x12\x12\n\x0e\x41\x43TION_MONITOR\x10\x01\x12\x11\n\rACTION_MANUAL\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATE']._serialized_start=560
  _globals['_STATE']._serialized_end=665
  _globals['_ACTION']._serialized_start=667
  _globals['_ACTION']._serialized_end=731
  _globals['_COMMAND']._serialized_start=112
  _globals['_COMMAND']._serialized_end=275
  _globals['_STATUS']._serialized_start=278
  _globals['_STATUS']._serialized_end=558
# @@protoc_insertion_point(module_scope)
