[platformio]
name = "Nucleo U0 Backscatter"
src_dir = .
include_dir = Inc

[env:u0]
build_src_filter =
  +<Src/*>
  +<Drivers/*>
  -<Drivers/CMSIS/*>
  +<startup_stm32u083xx.s>

build_flags = 
  -std=c++20
  -ffunction-sections
  -fdata-sections
  -DUX_INCLUDE_USER_DEFINE_FILE
  -DUSE_HAL_DRIVER
  -Wall
  -O3
  ; Drivers
  -I Drivers/STM32U0xx_HAL_Driver/Inc
  -I Drivers/STM32U0xx_HAL_Driver/Inc/Legacy
  -I Drivers/CMSIS/Include
  -I Drivers/CMSIS/Device/ST/STM32U0xx/Include
  -I Src/

board_build.ldscript = STM32U083xx_FLASH.ld

platform = ststm32
board = nucleo_u083rc
platform_packages =
  platformio/toolchain-gccarmnoneeabi@^1.140201.0
  tool-openocd
upload_protocol = stlink
debug_tool = stlink
debug_build_flags = -g
