[platformio]
src_dir = .
include_dir = Inc

[env:nucleo_g0b1re]
platform  = ststm32
board = nucleo_g0b1re

board_build.mcu = stm32g0b1vet6
board_build.f_cpu = 64000000L

framework = stm32cube
build_src_filter =
    +<src/*>
    +<Core/Src/*>
    +<lib/*>
    # FreeRTOS
    +<Middlewares/Third_Party/FreeRTOS/*>

build_flags =
    -IInc
    -Ilib
    -DUSE_HAL_DRIVER
    -DSTM32G0B1xx
    -std=c++17
    -Wunused-function
    # FreeRTOS
    -I Middlewares/Third_Party/FreeRTOS/Source/include
    -I Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0
    -I Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS
