[platformio]
src_dir = .
include_dir = Inc

[env:nucleo_g0b1re]
platform  = ststm32
board = nucleo_g0b1re

board_build.mcu = stm32g0b1vet6
board_build.f_cpu = 64000000L

framework = stm32cube
build_src_filter =
    +<src/*>
    +<Core/Src/*>
    +<lib/*>
    -<lib/**/test/*>
    # FreeRTOS
    +<Middlewares/Third_Party/FreeRTOS/*>

build_flags =
    -IInc
    -Ilib
    -DUSE_HAL_DRIVER
    -DSTM32G0B1xxl
    -std=c++17
    -Wunused-function
    # FreeRTOS
    -I Middlewares/Third_Party/FreeRTOS/Source/include
    -I Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0
    -I Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS

lib_deps =
  nanopb/Nanopb

custom_nanopb_protos =
  +<proto/base_station.proto>
  +<proto/backscatter.proto>
  +<proto/state.proto>

custom_nanopb_options =
  --error-on-unmatched
  --c-style

upload_protocol = dfu
upload_command = dfu-util -a 0 --dfuse-address 0x08000000:leave -D $SOURCE

platform_packages =
  tool-openocd

; upload_protocol = stlink
debug_tool = stlink
debug_build_flags = -g
