[platformio]
name = "M25PE10 Test"

[env:uno]
platform = atmelavr
board = uno
framework = arduino

board_build.mcu = atmega328p
board_build.f_cpu = 16000000L

upload_protocol = arduino
upload_speed = 115200
