[platformio]
name = "Blink"
src_dir = .
include_dir = Inc

[env:u0]
build_src_filter =
  +<Drivers/*>
  +<Src/*>
  +<startup_stm32u083xx.s>

build_flags = 
    -I Drivers/CMSIS/Include
    -I Drivers/CMSIS/Device/ST/STM32U0xx/Include
    -I Drivers/STM32U0xx_HAL_Driver/Inc
    -std=c++20

board_build.ldscript = STM32U083xx_FLASH.ld

platform = ststm32
board = nucleo_u083rc
platform_packages =
  platformio/toolchain-gccarmnoneeabi@^1.140201.0
  tool-openocd
upload_protocol = stlink
debug_tool = stlink
