#pragma once

#ifdef _AVR_IO_H_
#error "Include ov7670.hpp before avr/io.h"
#endif

#include <stdint.h>

namespace amber::ov7670 {

static constexpr uint8_t WRITE_ADDRESS = 0x42;
static constexpr uint8_t READ_ADDRESS = 0x43;

enum class reg : uint8_t {
    GAIN = 0x00,              // Gain control
    BLUE = 0x01,              // Blue channel gain
    RED = 0x02,               // Red channel gain
    VREF = 0x03,              // Vertical Frame Control
    COM1 = 0x04,              // Common Control 1
    BAVE = 0x05,              // U/B Average Level
    GbAVE = 0x06,             // Y/Gb Average Level
    AECHH = 0x07,             // Exposure Value
    RAVE = 0x08,              // V/R Average Level
    COM2 = 0x09,              // Common Control 2
    PID = 0x0A,               // Product ID MSB (read only)
    VER = 0x0B,               // Product ID LSB (read only)
    COM3 = 0x0C,              // Common Control 3
    COM4 = 0x0D,              // Common Control 4
    COM5 = 0x0E,              // Common Control 5
    COM6 = 0x0F,              // Common Control 6
    AECH = 0x10,              // Exposure Value
    CLKRC = 0x11,             // Internal Clock
    COM7 = 0x12,              // Common Control 7
    COM8 = 0x13,              // Common Control 8
    COM9 = 0x14,              // Common Control 9
    COM10 = 0x15,             // Common Control 10
    _RSVD16 = 0x16,           // Reserved
    HSTART = 0x17,            // Output Format - Horizontal Frame Start High
    HSTOP = 0x18,             // Output Format - Horiztonal Frame End High
    VSTRT = 0x19,             // Output Format - Vertical Frame Start High
    VSTOP = 0x1A,             // Output Format - Vertical Frame End High
    PSHFT = 0x1B,             // Data Format - Pixel Delay Select
    MIDH = 0x1C,              // Manufacturer ID High Byte
    MIDL = 0x1D,              // Manufacturer ID Low Byte
    MVFP = 0x1E,              // Mirror / VFlip Enable
    LAEC = 0x1F,              // Reserved
    ADCCTR0 = 0x20,           // ADC Control
    ADCCTR1 = 0x21,           // Reserved
    ADCCTR2 = 0x22,           // Reserved
    ADCCTR3 = 0x23,           // Reserved
    AEW = 0x24,               // AGC / AEC Stable Operating Region Upper Limit
    AEB = 0x25,               // AGC / AEC Stable Operating Region Lower Limit
    VPT = 0x26,               // AGC / AEC Fast Mode Operating Region
    BBIAS = 0x27,             // B Channel Signal Output Bias
    GbBIAS = 0x28,            // Gb Channel Signal Output Bias
    _RSVD29 = 0x29,           // Reserved
    EXHCH = 0x2A,             // Dummy Pixel Insert MSB
    EXHCL = 0x2B,             // Dummy Pixel Insert LSB
    RBIAS = 0x2C,             // R Channel Output Bias
    ADVFL = 0x2D,             // LSB of Insert Dummy Lines in Vertical Direction
    ADVFH = 0x2E,             // MSB of Insert Dummy Lines in Vertical Direction
    YAVE = 0x2F,              // Y/G Channel Average Value
    HSYST = 0x30,             // HSYNC Rising Edge Delay
    HSYEN = 0x31,             // HSYNC Falling Edge Delay
    HREF = 0x32,              // HREF Control,
    CHLF = 0x33,              // Reserved
    ARBLM = 0x34,             // Reserved,
    _RSVD35 = 0x35,           // Reserved
    _RSVD36 = 0x36,           // Reserved
    ADC = 0x37,               // Reserved
    ACOM = 0x38,              // Reserved
    OFON = 0x39,              // Reserved
    TSLB = 0x3A,              // Line Buffer Test Option
    COM11 = 0x3B,             // Common Control 11
    COM12 = 0x3C,             // Common Control 12
    COM13 = 0x3D,             // Common Control 13
    COM14 = 0x3E,             // Common Control 14,
    EDGE = 0x3F,              // Edge Enhancement Factor
    COM15 = 0x40,             // Common Control 15
    COM16 = 0x41,             // Common Control 16
    COM17 = 0x42,             // Common Control 17
    AWBC1 = 0x43,             // Reserved
    AWBC2 = 0x44,             // Reserved
    AWBC3 = 0x45,             // Reserved
    AWBC4 = 0x46,             // Reserved
    AWBC5 = 0x47,             // Reserved
    AWBC6 = 0x48,             // Reserved
    _RSVD49 = 0x49,           // Reserved
    _RSVD4A = 0x4A,           // Reserved
    REG4B = 0x4B,             // UV Average Enable
    DNSTH = 0x4C,             // Denoise Strength
    _RSVD4D = 0x4D,           // Reserved
    _RSVD4E = 0x4E,           // Reserved
    MTX1 = 0x4F,              // Matrix Coefficient 1
    MTX2 = 0x50,              // Matrix Coefficient 2
    MTX3 = 0x51,              // Matrix Coefficient 3
    MTX4 = 0x52,              // Matrix Coefficient 4
    MTX5 = 0x53,              // Matrix Coefficient 5
    MTX6 = 0x54,              // Matrix Coefficient 6
    BRIGHT = 0x55,            // Brightness Control
    CONTRAS = 0x56,           // Contrast Control
    CONTRAS_CENTER = 0x57,    // Contrast Center
    MTXS = 0x58,              // Matrix Coefficient Sign
    _RSVD59 = 0x59,           // Reserved
    _RSVD60 = 0x60,           // Reserved
    _RSVD61 = 0x61,           // Reserved
    LCC1 = 0x62,              // Length Correction 1
    LCC2 = 0x63,              // Length Correction 2
    LCC3 = 0x64,              // Length Correction 3
    LCC4 = 0x65,              // Length Correction 4
    LCC5 = 0x66,              // Length Correction 5
    MANU = 0x67,              // Manual U Value
    MANV = 0x68,              // Manual V Value
    GFIX = 0x69,              // Fix Gain Control
    GGAIN = 0x6A,             // G Channel AWB Gain
    DLBV = 0x6B,              // PLL Control
    AWBCTR3 = 0x6C,           // AWB Control 3
    AWBCTR2 = 0x6D,           // AWB Control 2
    AWBCTR1 = 0x6E,           // AWB Control 1
    AWBCTR0 = 0x6F,           // AWB Control 0
    SCALING_XSC = 0x70,       // X Scaling
    SCALING_YSC = 0x71,       // Y Scaling
    SCALING_DCWCTR = 0x72,    // DWC Control
    SCALING_PCLK_DIV = 0x73,  // DSP Clock Divider
    REG74 = 0x74,             // Digital Gain Manual Control
    REG75 = 0x75,             // Edge Enhancement Lower Limit
    REG76 = 0x76,             // Pixel Correction Enable
    REG77 = 0x77,             // Denoise Offset
    _RSVD78 = 0x78,           // Reserved
    _RSVD79 = 0x79,           // Reserved
    SLOP = 0x7A,              // Gamma Curve Highest Segment Slope
    GAM1 = 0x7B,              // Gamma Curve 1st Segment Input
    GAM2 = 0x7C,              // Gamma Curve 2nd Segment Input
    GAM3 = 0x7D,              // Gamma Curve 3rd Segment Input
    GAM4 = 0x7E,              // Gamma Curve 4th Segment Input
    GAM5 = 0x7F,              // Gamma Curve 5th Segment Input
    GAM6 = 0x80,              // Gamma Curve 6th Segment Input
    GAM7 = 0x81,              // Gamma Curve 7th Segment Input
    GAM8 = 0x82,              // Gamma Curve 8th Segment Input
    GAM9 = 0x83,              // Gamma Curve 9th Segment Input
    GAM10 = 0x84,             // Gamma Curve 10th Segment Input
    GAM11 = 0x85,             // Gamma Curve 11th Segment Input
    GAM12 = 0x86,             // Gamma Curve 12th Segment Input
    GAM13 = 0x87,             // Gamma Curve 13th Segment Input
    GAM14 = 0x88,             // Gamma Curve 14th Segment Input
    GAM15 = 0x89,             // Gamma Curve 15th Segment Input
    _RSVD8A = 0x8A,           // Reserved
    _RSVD8B = 0x8B,           // Reserved
    RGB444 = 0x8C,            // RGB444 Enable, Format
    _RSVD8D = 0x8D,           // Reserved
    _RSVD8E = 0x8E,           // Reserved
    _RSVD8F = 0x8F,           // Reserved
    _RSVD90 = 0x90,           // Reserved
    _RSVD91 = 0x91,           // Reserved
    DM_LNL = 0x92,            // Dummy Line low 8 bits
    DM_LNH = 0x93,            // Dummy Line high 8 bits
    LCC6 = 0x94,              // Lens Correction Option 6
    LCC7 = 0x95,              // Lens Correction Option 7
    _RSVD96 = 0x96,           // Reserved
    _RSVD97 = 0x97,           // Reserved
    _RSVD98 = 0x98,           // Reserved
    _RSVD99 = 0x99,           // Reserved
    _RSVD9A = 0x9A,           // Reserved
    _RSVD9B = 0x9B,           // Reserved
    _RSVD9C = 0x9C,           // Reserved
    BD50ST = 0x9D,            // 50 Hz Banding Filter Mode
    BD60ST = 0x9E,            // 60 Hz Banding Filter Mode
    HAECC1 = 0x9F,            // Histogram-based AGC Control 1
    HAECC2 = 0xA0,            // Histogram-based AGC Control 2
    _RSVDA1 = 0xA1,           // Reserved
    SCALING_PCLK_DELAY = 0xA2,  // Pixel Clock Delay
    _RSVDA3 = 0xA3,             // Reserved
    NT_CTRL = 0xA4,             // Auto Frame Rate Adjustment Control
    BD50MAX = 0xA5,             // 50 Hz Banding Step Limit
    HAECC3 = 0xA6,              // Histogram-based AGC Control 3
    HAECC4 = 0xA7,              // Histogram-based AGC Control 4
    HAECC5 = 0xA8,              // Histogram-based AGC Control 5
    HAECC6 = 0xA9,              // Histogram-based AGC Control 6
    HAECC7 = 0xAA,              // Histogram-based AGC Control 7
    BD60MAX = 0xAB,             // 60 Hz Banding Step Limit
    STR_OPT = 0xAC,             // Strobe Control Register AC
    STR_R = 0xAD,               // R Gain for LED Output Frame
    STR_G = 0xAE,               // G Gain for LED Output Frame
    STR_B = 0xAF,               // B Gain for LED Output Frame
    _RSVDB0 = 0xB0,             // Reserved
    ABLC1 = 0xB1,               // ABLC Enable
    _RSVDB2 = 0xB2,             // Reserved
    THL_ST = 0xB3,              // ALBC Target
    _RSVDB4 = 0xB4,             // Reserved
    THL_DLT = 0xB5,             // ABLC Stable Range
    _RSVDB6 = 0xB6,             // Reserved
    _RSVDB7 = 0xB7,             // Reserved
    _RSVDB8 = 0xB8,             // Reserved
    _RSVDB9 = 0xB9,             // Reserved
    _RSVDBA = 0xBA,             // Reserved
    _RSVDBB = 0xBB,             // Reserved
    _RSVDBC = 0xBC,             // Reserved
    _RSVDBD = 0xBD,             // Reserved
    AD_CHB = 0xBE,              // Blue Channel Black Level Compensation
    AD_CHR = 0xBF,              // Red Channel Black Level Compensation
    AD_CHGb = 0xC0,             // Gb Channel Black Level Compensation
    AD_CHGr = 0xC1,             // Gr Channel Black Level Compensation
    _RSVDC2 = 0xC2,             // Reserved
    _RSVDC3 = 0xC3,             // Reserved
    _RSVDC4 = 0xC4,             // Reserved
    _RSVDC5 = 0xC5,             // Reserved
    _RSVDC6 = 0xC6,             // Reserved
    _RSVDC7 = 0xC7,             // Reserved
    _RSVDC8 = 0xC8,             // Reserved
    SATCTR = 0xC9,              // Saturation Control
};

// designated array initializers are not supported in C++
// static constexpr uint8_t DEFAULT[reg::__COUNT] = {
//     [GAIN] = 0x00,
//     [BLUE] = 0x80,
//     [RED] = 0x80,
//     [VREF] = 0x03,
//     [COM1] = 0x00,
//     [BAVE] = 0x00,
//     [GbAVE] = 0x00,
//     [AECHH] = 0x07,
//     [RAVE] = 0x00,
//     [COM2] = 0x01,
//     [PID] = 0x76,
//     [VER] = 0x73,
//     [COM3] = 0x00,
//     [COM4] = 0x40,
//     [COM5] = 0x01,
//     [COM6] = 0x43,
//     [AECH] = 0x40,
//     [CLKRC] = 0x80,
//     [COM7] = 0x00,
//     [COM8] = 0x8f,
//     [COM9] = 0x4A,
//     [COM10] = 0x00,
//     [_RSVD16] = 0x00,
//     [HSTART] = 0x11,
//     [HSTOP] = 0x61,
//     [VSTRT] = 0x03,
//     [VSTOP] = 0x7B,
//     [PSHFT] = 0x00,
//     [MIDH] = 0x7f,
//     [MIDL] = 0xA2,
//     [MVFP] = 0x01,
//     [LAEC] = 0x00,
//     [ADCCTR0] = 0x04,
//     [ADCCTR1] = 0x02,
//     [ADCCTR2] = 0x01,
//     [ADCCTR3] = 0x00,
//     [AEW] = 0x75,
//     [AEB] = 0x63,
//     [VPT] = 0xD4,
//     [BBIAS] = 0x80,
//     [GbBIAS] = 0x80,
//     [_RSVD29] = 0x00,
//     [EXHCH] = 0x00,
//     [EXHCL] = 0x2B,
//     [RBIAS] = 0x80,
//     [ADVFL] = 0x00,
//     [ADVFH] = 0x00,
//     [YAVE] = 0x00,
//     [HSYST] = 0x08,
//     [HSYEN] = 0x30,
//     [HREF] = 0x80,
//     [CHLF] = 0x08,
//     [ARBLM] = 0x11,
//     [_RSVD35] = 0x00,
//     [_RSVD36] = 0x00,
//     [ADC] = 0x3f,
//     [ACOM] = 0x01,
//     [OFON] = 0x00,
//     [TSLB] = 0x0D,
//     [COM11] = 0x00,
//     [COM12] = 0x68,
//     [COM13] = 0x88,
//     [COM14] = 0x00,
//     [EDGE] = 0x00,
//     [COM15] = 0xC0,
//     [COM16] = 0x08,
//     [COM17] = 0x00,
//     [AWBC1] = 0x14,
//     [AWBC2] = 0xF0,
//     [AWBC3] = 0x45,
//     [AWBC4] = 0x61,
//     [AWBC5] = 0x51,
//     [AWBC6] = 0x79,
//     [_RSVD49] = 0x00,
//     [_RSVD4A] = 0x00,
//     [REG4B] = 0x00,
//     [DNSTH] = 0x00,
//     [_RSVD4D] = 0x00,
//     [_RSVD4E] = 0x00,
//     [MTX1] = 0x40,
//     [MTX2] = 0x34,
//     [MTX3] = 0xC0,
//     [MTX4] = 0x17,
//     [MTX5] = 0x29,
//     [MTX6] = 0x40,
//     [BRIGHT] = 0x00,
//     [CONTRAS] = 0x40,
//     [CONTRAS_CENTER] = 0x80,
//     [MTXS] = 0x1E,
//     [_RSVD59] = 0x00,
//     [_RSVD60] = 0x00,
//     [_RSVD61] = 0x00,
//     [LCC1] = 0x00,
//     [LCC2] = 0x00,
//     [LCC3] = 0x50,
//     [LCC4] = 0x30,
//     [LCC5] = 0x00,
//     [MANU] = 0x80,
//     [MANV] = 0x80,
//     [GFIX] = 0x00,
//     [GGAIN] = 0x00,
//     [DLBV] = 0x0A,
//     [AWBCTR3] = 0x02,
//     [AWBCTR2] = 0x55,
//     [AWBCTR1] = 0xC0,
//     [AWBCTR0] = 0x9A,
//     [SCALING_XSC] = 0x3A,
//     [SCALING_YSC] = 0x35,
//     [SCALING_DCWCTR] = 0x11,
//     [SCALING_PCLK_DIV] = 0x00,
//     [REG74] = 0x00,
//     [REG75] = 0x0F,
//     [REG76] = 0x01,
//     [REG77] = 0x10,
//     [_RSVD78] = 0x00,
//     [_RSVD79] = 0x00,
//     [SLOP] = 0x24,
//     [GAM1] = 0x04,
//     [GAM2] = 0x07,
//     [GAM3] = 0x10,
//     [GAM4] = 0x28,
//     [GAM5] = 0x36,
//     [GAM6] = 0x44,
//     [GAM7] = 0x52,
//     [GAM8] = 0x60,
//     [GAM9] = 0x6C,
//     [GAM10] = 0x78,
//     [GAM11] = 0x8C,
//     [GAM12] = 0x9E,
//     [GAM13] = 0xBB,
//     [GAM14] = 0xD2,
//     [GAM15] = 0xE5,
//     [_RSVD8A] = 0x00,
//     [_RSVD8B] = 0x00,
//     [RGB444] = 0x00,
//     [_RSVD8D] = 0x00,
//     [_RSVD8E] = 0x00,
//     [_RSVD8F] = 0x00,
//     [_RSVD90] = 0x00,
//     [_RSVD91] = 0x00,
//     [DM_LNL] = 0x00,
//     [DM_LNH] = 0x00,
//     [LCC6] = 0x50,
//     [LCC7] = 0x50,
//     [_RSVD96] = 0x00,
//     [_RSVD97] = 0x00,
//     [_RSVD98] = 0x00,
//     [_RSVD99] = 0x00,
//     [_RSVD9A] = 0x00,
//     [_RSVD9B] = 0x00,
//     [_RSVD9C] = 0x00,
//     [BD50ST] = 0x99,
//     [BD60ST] = 0x7F,
//     [HAECC1] = 0xC0,
//     [HAECC2] = 0x90,
//     [_RSVDA1] = 0x00,
//     [SCALING_PCLK_DELAY] = 0x02,
//     [_RSVDA3] = 0x00,
//     [NT_CTRL] = 0x00,
//     [BD50MAX] = 0x0F,
//     [HAECC3] = 0xF0,
//     [HAECC4] = 0xC1,
//     [HAECC5] = 0xF0,
//     [HAECC6] = 0xC1,
//     [HAECC7] = 0x14,
//     [BD60MAX] = 0x0F,
//     [STR_OPT] = 0x00,
//     [STR_R] = 0x80,
//     [STR_G] = 0x80,
//     [STR_B] = 0x80,
//     [_RSVDB0] = 0x00,
//     [ABLC1] = 0x00,
//     [_RSVDB2] = 0x00,
//     [THL_ST] = 0x80,
//     [_RSVDB4] = 0x00,
//     [THL_DLT] = 0x04,
//     [_RSVDB6] = 0x00,
//     [_RSVDB7] = 0x00,
//     [_RSVDB8] = 0x00,
//     [_RSVDB9] = 0x00,
//     [_RSVDBA] = 0x00,
//     [_RSVDBB] = 0x00,
//     [_RSVDBC] = 0x00,
//     [_RSVDBD] = 0x00,
//     [AD_CHB] = 0x00,
//     [AD_CHR] = 0x00,
//     [AD_CHGb] = 0x00,
//     [AD_CHGr] = 0x00,
//     [_RSVDC2] = 0x00,
//     [_RSVDC3] = 0x00,
//     [_RSVDC4] = 0x00,
//     [_RSVDC5] = 0x00,
//     [_RSVDC6] = 0x00,
//     [_RSVDC7] = 0x00,
//     [_RSVDC8] = 0x00,
//     [SATCTR] = 0xC0,
// };

}  // namespace amber::ov7670