[platformio]
name = "spi-connect"
description = "Test SPI functionality with ice40up5k using damdoy spi_hw example."

[env:arduino]
platform = atmelavr
framework = arduino
board = uno

board_build.mcu = atmega328p
board_build.f_cpu = 16000000L

upload_protocol = arduino
upload_speed = 115200

build_unflags = -std=gnu++11
build_flags = -std=c++14