{
 "title": "Satellite",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "State",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT \"state\" FROM \"mock\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "SELECT \"battery\" FROM \"mock\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "SELECT \"fpga\", \"mcu\", \"camera\",\"antenna\" FROM \"mock\" WHERE $timeFilter"
    }
   ]
  }
 ]
}