[platformio]
name = "SPI Flash"
src_dir = .
include_dir = Inc

[env:u0]
build_src_filter =
  +<Src/*>
  +<Drivers/*>
  +<startup_stm32u083xx.s>
  # FreeRTOS
  +<Middlewares/Third_Party/CMSIS/*>
  +<Middlewares/Third_Party/FreeRTOS/*>
  # USB Middleware
  +<stm32-mw-usb-device/Core/Src/*>
  +<stm32-mw-usb-device/Class/CDC/Src/*>
  # Exclude template files. They are copied and implemented in the Src/ folder
  -<stm32-mw-usb-device/Core/Src/usbd_conf_template.c>
  -<stm32-mw-usb-device/Core/Src/usbd_desc_template.c>
  -<stm32-mw-usb-device/Class/CDC/Src/usbd_cdc_if_template.c>

build_flags = 
  -std=c++20
  -DUX_INCLUDE_USER_DEFINE_FILE
  -DUSE_HAL_DRIVER
  -Wall
  ; Drivers
  -I Drivers/STM32U0xx_HAL_Driver/Inc
  -I Drivers/STM32U0xx_HAL_Driver/Inc/Legacy
  -I Drivers/CMSIS/Include
  -I Drivers/CMSIS/Device/ST/STM32U0xx/Include
  ; FreeRTOS
  -I Middlewares/Third_Party/CMSIS/RTOS2/Include
  -I Middlewares/Third_Party/FreeRTOS/Source/include
  -I Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM0
  ; USB Device
  -I stm32-mw-usb-device/Core/Inc
  -I stm32-mw-usb-device/Class/CDC/Inc
  -I Src/
  -I Src/mw-usb

board_build.ldscript = STM32U083xx_FLASH.ld

lib_deps =
  nanopb/Nanopb

custom_nanopb_protos =
  +<proto/spi_flash.proto>

custom_nanopb_options =
  --error-on-unmatched
  --c-style

platform = ststm32
board = nucleo_u083rc
platform_packages =
  platformio/toolchain-gccarmnoneeabi@^1.140201.0
  tool-openocd
upload_protocol = stlink
debug_tool = stlink
debug_build_flags = -g
