[platformio]
name = "Camera Streaming"
description = "Send artificial image data over Serial."

[env:uno]
platform = atmelavr
board = uno
framework = arduino

board_build.mcu = atmega328p
board_build.f_cpu = 16000000L

upload_protocol = arduino
upload_speed = 115200

build_unflags = -std=gnu++11
build_flags = -std=c++14
