# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spi_flash.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'spi_flash.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fspi_flash.proto\x12\tspi_flash\"\x18\n\x07\x43ommand\x12\r\n\x05value\x18\x01 \x01(\r\"\x9e\x01\n\x06Status\x12\x12\n\ntx_counter\x18\x01 \x01(\r\x12\x12\n\nrx_counter\x18\x02 \x01(\r\x12\x18\n\x10temperature_degc\x18\x03 \x01(\x05\x12\x0f\n\x07vbat_mv\x18\x04 \x01(\x05\x12\x12\n\nvrefint_mv\x18\x05 \x01(\x05\x12\x1f\n\x05state\x18\x06 \x01(\x0e\x32\x10.spi_flash.State\x12\x0c\n\x04\x65\x63ho\x18\x07 \x01(\r*T\n\x05State\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04IDLE\x10\x01\x12\r\n\tRECEIVING\x10\x02\x12\x0b\n\x07WRITING\x10\x03\x12\x0b\n\x07READING\x10\x04\x12\x0b\n\x07\x45RASING\x10\x05\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spi_flash_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATE']._serialized_start=217
  _globals['_STATE']._serialized_end=301
  _globals['_COMMAND']._serialized_start=30
  _globals['_COMMAND']._serialized_end=54
  _globals['_STATUS']._serialized_start=57
  _globals['_STATUS']._serialized_end=215
# @@protoc_insertion_point(module_scope)
