# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spi_flash.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'spi_flash.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fspi_flash.proto\x12\tspi_flash\";\n\x04Page\x12\x13\n\x0bpage_number\x18\x01 \x01(\r\x12\x10\n\x08\x64\x61ta_crc\x18\x02 \x01(\x07\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"a\n\x07\x43ommand\x12!\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x11.spi_flash.Action\x12\x1d\n\x04page\x18\x02 \x01(\x0b\x32\x0f.spi_flash.Page\x12\x14\n\x0cpage_request\x18\x03 \x01(\r\"\xa6\x01\n\x06Status\x12\x12\n\ntx_counter\x18\x01 \x01(\r\x12\x12\n\nrx_counter\x18\x02 \x01(\r\x12\x18\n\x10temperature_degc\x18\x03 \x01(\x05\x12\x0f\n\x07vbat_mv\x18\x04 \x01(\x05\x12\x12\n\nvrefint_mv\x18\x05 \x01(\x05\x12\x1f\n\x05state\x18\x06 \x01(\x0e\x32\x10.spi_flash.State\x12\x14\n\x0cpage_request\x18\x07 \x01(\r*?\n\x06\x41\x63tion\x12\x0f\n\x0b\x41\x43TION_NONE\x10\x00\x12\x10\n\x0c\x41\x43TION_FLASH\x10\x01\x12\x12\n\x0e\x41\x43TION_READOUT\x10\x02*Q\n\x05State\x12\x11\n\rSTATE_UNKNOWN\x10\x00\x12\x0e\n\nSTATE_IDLE\x10\x01\x12\x12\n\x0eSTATE_FLASHING\x10\x02\x12\x11\n\rSTATE_READOUT\x10\x03\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spi_flash_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTION']._serialized_start=359
  _globals['_ACTION']._serialized_end=422
  _globals['_STATE']._serialized_start=424
  _globals['_STATE']._serialized_end=505
  _globals['_PAGE']._serialized_start=30
  _globals['_PAGE']._serialized_end=89
  _globals['_COMMAND']._serialized_start=91
  _globals['_COMMAND']._serialized_end=188
  _globals['_STATUS']._serialized_start=191
  _globals['_STATUS']._serialized_end=357
# @@protoc_insertion_point(module_scope)
